### ISSUE TITLE
Fails on Ubuntu Yakkety 16.10 and Zesty 17.04

### ISSUE THREAD

**Issue by florianparain** [threatstack/threatstack-ansible#31]
It works great on Ubuntu Xenial 16.04.
It fails on Ubuntu Yakkety 16.10 and Zesty 17.04.

Below is the Ansible logs and stack trace.

I've installed the version 3.1.0.

```
  roles:
    - role: threatstack.threatstack-ansible
      threatstack_configure_agent: false
```

```
TASK [threatstack.threatstack-ansible : python-apt dependency.]
ok: [default]

TASK [threatstack.threatstack-ansible : apt-transport-https dependency.]
ok: [default]

TASK [threatstack.threatstack-ansible : Add Threat Stack apt repository key.]
changed: [default]

TASK [threatstack.threatstack-ansible : Add Threat Stack apt repository.]
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: Shared connection to 127.0.0.1 closed.
fatal: [default]: FAILED!

Traceback (most recent call last):
  File "/tmp/ansible_tb3AJK/ansible_module_apt_repository.py", line 565, in <module>
    main()
  File "/tmp/ansible_tb3AJK/ansible_module_apt_repository.py", line 553, in main
    cache.update()
  File "/usr/lib/python2.7/dist-packages/apt/cache.py", line 464, in update
    raise FetchFailedException(e)
apt.cache.FetchFailedException: E:The repository 'https://pkg.threatstack.com/Ubuntu zesty Release' does not have a Release file.
Shared connection to 127.0.0.1 closed.
```

**Comment by florianparain** [comment]
Answer from Threat Stack support:

At the moment, we don't support Ubuntu Yakkety or Zesty, and don't have individual packages for either of them. You can find a full list of all of our supported OS's here: https://threatstack.zendesk.com/hc/en-us/articles/200343805-Supported-Operating-Systems-Kernels.
That being said, while not officially supported, our Xenial package will likely work properly on both of those OS's. If you wanted to give this a try, you can edit tasks/apt_install.yml in the threatstack-ansible.yml. Just change the line `repo: "deb {{ threatstack_pkg_url }}/Ubuntu {{ ansible_distribution_release }} main"` to `repo: "deb {{ threatstack_pkg_url }}/Ubuntu xenial main"`, and it will download our xenial package.

**Comment by pkaeding** [comment]
I'm getting a similar error on Xenial (16.04 LTS):

```TASK [threatstack.threatstack-ansible : Add ThreatStack apt repository] *****************************************************************************************************************************************************************************************************************************
Wednesday 04 September 2019  11:40:35 -0700 (0:00:02.691)       0:00:18.029 *** 
fatal: [10.10.1.186]: FAILED! => changed=false 
  module_stderr: ''
  module_stdout: |-
    Traceback (most recent call last):
      File "/tmp/ansible_MY1RJY/ansible_module_apt_repository.py", line 551, in <module>
        main()
      File "/tmp/ansible_MY1RJY/ansible_module_apt_repository.py", line 543, in main
        cache.update()
      File "/usr/lib/python2.7/dist-packages/apt/cache.py", line 440, in update
        raise FetchFailedException(e)
    apt.cache.FetchFailedException: W:Failed to fetch https://pkg.threatstack.com/v2/Ubuntu/dists/trusty/InRelease  Unable to find expected entry 'main/binary-amd64/Packages' in Release file (Wrong sources.list entry or malformed file)
    , E:Some index files failed to download. They have been ignored, or old ones used instead.
  msg: MODULE FAILURE
  rc: 1
```

Any ideas?
